---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: gateway-api
  namespace: team-gateway-dev
  labels:
    app.kubernetes.io/name: gateway-api
    app.kubernetes.io/part-of: gitops-platform
    tenant: team-gateway
automountServiceAccountToken: false
