---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: auth-api
  namespace: team-auth-dev
  labels:
    app.kubernetes.io/name: auth-api
    app.kubernetes.io/part-of: gitops-platform
    tenant: team-auth
  # annotations:
  #   eks.amazonaws.com/role-arn: arn:aws:iam::ACCOUNT_ID:role/auth-api-role
automountServiceAccountToken: false
