---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - metrics-server-patch.yaml
  - ingress-nginx-helmrepo.yaml
  - ingress-nginx-helmrelease.yaml
  - flux-webhook-receiver.yaml
